version: '3'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: GetSchwifty
    volumes:
      - db:/var/lib/mysql

  web:
    image: training
    build: .
    depends_on:
      - mysql
      - adminer
    links:
      - mysql
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    env_file:
      - .training.env
    tty: true
    stdin_open: true

  adminer:
    image: adminer
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=flat

volumes:
  db:
