default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] || 'root' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'GetSchwifty' %>
  port: <%= ENV['DATABASE_PORT'] || 3306 %>
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'training_development' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'training_test' %>

spec:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'training_development' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>